### ISSUE TITLE
Failure when no Internet

### ISSUE THREAD

**Issue by dmgerman** [TobiasZawada/org-yt#2]
Thank you for the extension, I really appreciate. I'll try to submit a patch for it.

When there is no Internet an error is created.

This is problematic when traversing the agenda. 

1. No internet
2. one runs agenda
3. a file with a yt link is traversed 

at this point an error is created, stopping the agenda.

Ideally it needs to gracefully submit a warning but not generate an error. 

Potential solution: wrap the code with an exception handler.

**Comment by dmgerman** [comment]
I was thinking that perhaps the problem is not  only the lack of internet, but that the thumbnails cannot not cached.

**Comment by TobiasZawada** [comment]
I have merged your pull-request with some review.
Caching is now the default.
Cache size is limited (by number of files).

**Comment by TobiasZawada** [comment]
I'll close this issue when you have tested it and report here your test result.

A potential improvement would be to load the thumbnail images asynchronously. But that would require some more work.

**Comment by dmgerman** [comment]
It works well. Thank you very much. 

I am not sure it is worth the extra effort of doing asynchronously. With these changes, a user will probably add few videos at a time, and (at least for me) the download is _very_ fast.

**Comment by TobiasZawada** [comment]
The download is very fast if there is an online connection. But, in the case that the computer is offline, the download attempts can take a long time until timeout. In my experience Emacs is blocked in this time.

But, I close this issue now. The asynchronous-thing is another topic.
